language: android
android:
  components:
    - platform-tools
    - build-tools-22.0.1
    - android-22
    - add-on
    - extra
    - extra-android-support
    - extra-google-google_play_services
    - sys-img-armeabi-v7a-android-22
before_script:
  - ./wait_for_emulator
