language: android
jdk: oraclejdk8
env:
  matrix:
    - ANDROID_TARGET=android-22  ANDROID_ABI=armeabi-v7a
  global:
     # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
     - secure: "KrvvTUepiJ71g3cdM/CBGqlHCh3jUJqVguIX4vReaINW0SDBHktLTSDBn9y+vjSS8QbAOWqFhioySVS+6WVA4+eBM7N0Pjx4bo0SbYytmDFhSffXlc6hlluGzykhMzFCtCXCliOVAlFXs2aIuhKwp45WFT4Lu6qn1SJiNJ9iJKuzHzTNSob/w61be+vy/onLnbmZ3Dz4gSr9FDpLTonbHS3vGvLxQuepKPpCcybZJDTTtAl3OPqTPdaDGRY+D9IsSQSWGgyrcquRwOousUOdIm36+HjHZs+DI7TcJBe1111bNW1wEQ/1MAWx4SMAn2Th3x593q+HK5k/jIhW1b5qIEIzEyQBo+a3PEKxvgu2Bdo2/dJrJIQ0Ktxj5GeIKyLG4CPkmW/qEuY7J4Egk6EuEXZjWEU7pPAGY3Bg5WbI4vHx8dyHYPkNRfSRSQntM12cFibVDWZ7JmyKi0Fxr0YVTi8UWHGCOUd7G++nb6UuoyegR1yaloyWjrAx9+S6sHC1VvJvFC2JLaeojqcTfznLm+6A2f8QTbSL/Vhyva89Pr8TWDvfWEiv+YtKgfRpvLr9s1sFjXMzDJ7yOlR0RovZaK89jSE1F9JQ3AcG1yqgutaCJaKsuta0jRfbjWEmDy2SB5L6RsOaxROSMqkobMXbAmxT2r0t0FvXb4L1pL6hmWY="
android:
  components:
    - build-tools-22.0.1
    - android-22
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-google-google_play_services
    - sys-img-armeabi-v7a-android-22
before_script:
    - echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a
    - emulator -avd test -no-skin -no-audio -no-window &
    - android-wait-for-emulator
    - adb shell input keyevent 82 &
notifications:
    hipchat: 9a2ee1a055d11705229e675c791952@Travis
    email: false
addons:
  coverity_scan:
    project:
      name: "just-zed/dimentia-smart-watch"
      description: "Build submitted via Travis CI"
    build_command_prepend: "mvn clean"
    build_command:   "mvn -DskipTests=true compile"
    branch_pattern: coverity_scan